apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: airflow
    meta.helm.sh/release-namespace: investment-assistant
  creationTimestamp: "2025-06-29T15:25:40Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: airflow-1.11.0
    component: scheduler
    heritage: Helm
    release: airflow
    tier: airflow
  name: airflow-scheduler
  namespace: investment-assistant
  resourceVersion: "659534"
  uid: 6b4e7ea7-5e3b-4ba5-80ab-9f8f559cf935
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: task-logs
    port: 8793
    protocol: TCP
    targetPort: 8793
  selector:
    component: scheduler
    release: airflow
    tier: airflow
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
