apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: airflow
    meta.helm.sh/release-namespace: investment-assistant
  creationTimestamp: "2025-06-29T15:25:40Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: airflow-1.11.0
    component: webserver
    heritage: Helm
    release: airflow
    tier: airflow
  name: airflow-webserver
  namespace: investment-assistant
  resourceVersion: "659536"
  uid: d211cc27-5d87-41db-b7d5-3eef4d6d4649
spec:
  clusterIP: 10.43.5.78
  clusterIPs:
  - 10.43.5.78
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: airflow-ui
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: webserver
    release: airflow
    tier: airflow
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
