# S&P 500 WebSocket Consumer
# 10개 Producer Pod에서 전송되는 데이터를 통합 처리

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sp500-websocket-consumer-code
  namespace: investment-assistant
  labels:
    app: sp500-websocket-consumer
data:
  consumer.py: |
    import json
    import os
    import time
    from kafka import KafkaConsumer
    import psycopg2
    import logging

    # 로깅 설정
    logging.basicConfig(level=logging.INFO, format='%(asctime)s [%(levelname)s] %(message)s')
    logger = logging.getLogger(__name__)

    class SP500WebSocketConsumer:
        def __init__(self):
            self.kafka_servers = os.getenv('KAFKA_SERVERS')
            self.topic = "sp500-websocket-trades"
            
            # 통계
            self.processed_count = 0
            self.error_count = 0
            self.start_time = time.time()
            
            # API 키별 통계
            self.api_key_stats = {}
            
            logger.info("🚀 S&P 500 WebSocket Consumer 초기화")
            logger.info(f"   📡 Topic: {self.topic}")
            logger.info(f"   🔗 Kafka: {self.kafka_servers}")
            
        def get_db_connection(self):
            """PostgreSQL 연결"""
            return psycopg2.connect(
                host=os.getenv('POSTGRES_HOST'),
                database=os.getenv('POSTGRES_DB'),
                user=os.getenv('POSTGRES_USER'),
                password=os.getenv('POSTGRES_PASSWORD'),
                port=5432
            )
        
        def safe_numeric(self, value):
            """안전한 숫자 변환"""
            if value is None or value == '':
                return None
            try:
                return float(value)
            except (ValueError, TypeError):
                return None
        
        def safe_integer(self, value):
            """안전한 정수 변환"""
            if value is None or value == '':
                return None
            try:
                return int(value)
            except (ValueError, TypeError):
                return None
        
        def insert_trade_data(self, data):
            """S&P 500 WebSocket 거래 데이터 삽입"""
            conn = None
            try:
                conn = self.get_db_connection()
                with conn.cursor() as cursor:
                    insert_sql = '''
                        INSERT INTO sp500_websocket_trades (
                            symbol, price, volume, timestamp_ms, trade_conditions,
                            api_key_index, pod_name, source, created_at
                        ) VALUES (
                            %(symbol)s, %(price)s, %(volume)s, %(timestamp_ms)s, %(trade_conditions)s,
                            %(api_key_index)s, %(pod_name)s, %(source)s, NOW()
                        )
                        ON CONFLICT (symbol, timestamp_ms) DO NOTHING
                    '''
                    
                    params = {
                        'symbol': data.get('symbol'),
                        'price': self.safe_numeric(data.get('price')),
                        'volume': self.safe_integer(data.get('volume')),
                        'timestamp_ms': self.safe_integer(data.get('timestamp_ms')),
                        'trade_conditions': data.get('trade_conditions', []),
                        'pod_index': self.safe_integer(data.get('pod_index')),
                        'pod_name': data.get('pod_name'),
                        'source': data.get('source', 'finnhub_sp500_websocket')
                    }
                    
                    cursor.execute(insert_sql, params)
                    conn.commit()
                    
                    # Pod Index별 통계 업데이트
                    pod_index = self.safe_integer(data.get('pod_index'))
                    if pod_index:
                        if pod_index not in self.api_key_stats:
                            self.api_key_stats[pod_index] = {'count': 0, 'symbols': set()}
                        
                        self.api_key_stats[pod_index]['count'] += 1
                        self.api_key_stats[pod_index]['symbols'].add(params['symbol'])
                    
                    return True
                    
            except psycopg2.errors.UniqueViolation:
                # 중복 데이터는 정상적인 상황 (같은 거래가 여러 번 수신될 수 있음)
                if conn:
                    conn.rollback()
                return True
                
            except Exception as e:
                logger.error(f"❌ DB 삽입 실패: {e}")
                logger.error(f"   데이터: {data}")
                if conn:
                    conn.rollback()
                return False
                
            finally:
                if conn:
                    conn.close()
        
        def log_detailed_statistics(self):
            """상세 통계 로깅"""
            if not self.api_key_stats:
                return
                
            elapsed = time.time() - self.start_time
            overall_rate = self.processed_count / elapsed if elapsed > 0 else 0
            current_time = time.strftime("%H:%M:%S")
            
            logger.info(f"📊 === S&P 500 Consumer 상세 통계 ({current_time}) ===")
            logger.info(f"   전체: {self.processed_count}개 처리, {self.error_count}개 에러, {overall_rate:.1f}/sec")
            
            # Pod Index별 통계
            total_symbols = set()
            for pod_index in sorted(self.api_key_stats.keys()):
                stats = self.api_key_stats[pod_index]
                count = stats['count']
                symbols = stats['symbols']
                rate = count / elapsed if elapsed > 0 else 0
                
                logger.info(f"   Pod-{pod_index}: {count}개 메시지, {len(symbols)}개 심볼, {rate:.1f}/sec")
                total_symbols.update(symbols)
            
            logger.info(f"   총 활성 심볼: {len(total_symbols)}개")
            logger.info("   " + "="*50)
        
        def run(self):
            """메인 Consumer 실행"""
            try:
                consumer = KafkaConsumer(
                    self.topic,
                    bootstrap_servers=self.kafka_servers,
                    value_deserializer=lambda m: json.loads(m.decode('utf-8')),
                    key_deserializer=lambda m: m.decode('utf-8') if m else None,
                    group_id='sp500-websocket-consumer-group',
                    auto_offset_reset='latest',
                    enable_auto_commit=True,
                    session_timeout_ms=30000,
                    heartbeat_interval_ms=10000
                )
                
                logger.info("🔄 S&P 500 WebSocket Consumer 시작")
                logger.info(f"   📡 구독 Topic: {self.topic}")
                logger.info(f"   👥 Consumer Group: sp500-websocket-consumer-group")
                
                last_stats_time = time.time()
                stats_interval = 60  # 1분마다 상세 통계
                
                for message in consumer:
                    try:
                        data = message.value
                        symbol = data.get('symbol', 'UNKNOWN')
                        api_key_index = data.get('api_key_index', 0)
                        pod_name = data.get('pod_name', 'unknown')
                        
                        if self.insert_trade_data(data):
                            self.processed_count += 1
                            
                            # 간단한 진행 상황 (100개마다)
                            if self.processed_count % 100 == 0:
                                elapsed = time.time() - self.start_time
                                rate = self.processed_count / elapsed if elapsed > 0 else 0
                                current_time = time.strftime("%H:%M:%S")
                                logger.info(f"📈 처리: {self.processed_count}, 에러: {self.error_count}, "
                                          f"시간: {current_time}, 속도: {rate:.1f}/sec")
                            
                        else:
                            self.error_count += 1
                        
                        # 상세 통계 (1분마다)
                        current_time = time.time()
                        if current_time - last_stats_time >= stats_interval:
                            self.log_detailed_statistics()
                            last_stats_time = current_time
                            
                    except Exception as e:
                        logger.error(f"❌ 메시지 처리 오류: {e}")
                        logger.error(f"   메시지: {message.value}")
                        self.error_count += 1

            except KeyboardInterrupt:
                logger.info("🛑 사용자 중단 요청")
                
            except Exception as e:
                logger.error(f"❌ Consumer 실행 오류: {e}")
                
            finally:
                # 최종 통계
                elapsed = time.time() - self.start_time
                logger.info("✅ S&P 500 WebSocket Consumer 종료")
                logger.info(f"   최종 통계: {self.processed_count}개 처리, {self.error_count}개 에러")
                logger.info(f"   실행 시간: {elapsed:.1f}초")
                
                if self.api_key_stats:
                    logger.info("   Pod별 최종 통계:")
                    for pod_index in sorted(self.api_key_stats.keys()):
                        stats = self.api_key_stats[pod_index]
                        logger.info(f"     Pod-{pod_index}: {stats['count']}개, {len(stats['symbols'])}개 심볼")

    if __name__ == "__main__":
        consumer = SP500WebSocketConsumer()
        consumer.run()

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sp500-websocket-consumer
  namespace: investment-assistant
  labels:
    app: sp500-websocket-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sp500-websocket-consumer
  template:
    metadata:
      labels:
        app: sp500-websocket-consumer
    spec:
      containers:
      - name: websocket-consumer
        image: python:3.11-slim
        command: ["sh", "-c"]
        args:
        - |
          apt-get update && apt-get install -y procps
          pip install --no-cache-dir kafka-python psycopg2-binary lz4
          python /app/consumer.py
        env:
        # Kafka 설정
        - name: KAFKA_SERVERS
          value: "my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
          
        # PostgreSQL 설정  
        - name: POSTGRES_HOST
          value: "postgresql.investment-assistant.svc.cluster.local"
        - name: POSTGRES_DB
          value: "investment_db"
        - name: POSTGRES_USER
          value: "airflow"
        - name: POSTGRES_PASSWORD
          value: "airflow123"
          
        volumeMounts:
        - name: consumer-code
          mountPath: /app
          
        resources:
          requests:
            memory: "512Mi"  # Consumer는 더 많은 메모리 필요
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
            
        livenessProbe:
          exec:
            command: ["pgrep", "-f", "consumer.py"]
          initialDelaySeconds: 60
          periodSeconds: 60
          failureThreshold: 3
          
        readinessProbe:
          exec:
            command: ["pgrep", "-f", "consumer.py"]
          initialDelaySeconds: 30
          periodSeconds: 30
          
      volumes:
      - name: consumer-code
        configMap:
          name: sp500-websocket-consumer-code
          
      restartPolicy: Always