apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"name":"airflow-scheduler","namespace":"investment-assistant"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"airflow","component":"scheduler","tier":"airflow"}},"serviceName":"airflow-scheduler-headless","template":{"metadata":{"labels":{"app":"airflow","component":"scheduler","tier":"airflow"}},"spec":{"containers":[{"command":["/bin/bash","-c","airflow scheduler\n"],"env":[{"name":"AIRFLOW__DATABASE__SQL_ALCHEMY_CONN","value":"postgresql+psycopg2://airflow:airflow123@postgresql.investment-assistant.svc.cluster.local:5432/airflow"},{"name":"AIRFLOW__CORE__FERNET_KEY","valueFrom":{"secretKeyRef":{"key":"fernet-key","name":"airflow-secret"}}}],"image":"apache/airflow:2.8.1-python3.11","name":"scheduler","resources":{"limits":{"cpu":"1000m","memory":"2Gi"},"requests":{"cpu":"500m","memory":"1Gi"}},"volumeMounts":[{"mountPath":"/opt/airflow/dags","name":"dags-storage"},{"mountPath":"/opt/airflow/logs","name":"logs"}]}],"nodeSelector":{"kubernetes.io/hostname":"k3s-server-1"},"securityContext":{"fsGroup":0,"runAsUser":50000},"volumes":[{"hostPath":{"path":"/home/spark/investment-assistant-project/investment-service/dags","type":"Directory"},"name":"dags-storage"}]}},"volumeClaimTemplates":[{"metadata":{"name":"logs"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"local-path"}}]}}
  creationTimestamp: "2025-07-07T15:10:49Z"
  generation: 5
  name: airflow-scheduler
  namespace: investment-assistant
  resourceVersion: "1506774"
  uid: d79bfbb6-6316-496e-82dd-9e6b297c58b1
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: airflow
      component: scheduler
      tier: airflow
  serviceName: airflow-scheduler-headless
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: airflow
        component: scheduler
        tier: airflow
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - |
          airflow scheduler
        env:
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: postgresql+psycopg2://airflow:airflow123@postgresql.investment-assistant.svc.cluster.local:5432/airflow
        - name: AIRFLOW__CORE__FERNET_KEY
          valueFrom:
            secretKeyRef:
              key: fernet-key
              name: airflow-secret
        image: apache/airflow:2.8.1-python3.11
        imagePullPolicy: IfNotPresent
        name: scheduler
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/airflow/dags
          name: dags-storage
        - mountPath: /opt/airflow/logs
          name: logs
      dnsPolicy: ClusterFirst
      nodeName: k3s-server-1
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 0
        runAsUser: 50000
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /home/spark/investment-assistant-project/investment-service/dags
          type: Directory
        name: dags-storage
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: logs
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: local-path
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  availableReplicas: 0
  collisionCount: 0
  currentReplicas: 1
  currentRevision: airflow-scheduler-c59c8b764
  observedGeneration: 5
  replicas: 1
  updateRevision: airflow-scheduler-c59c8b764
  updatedReplicas: 1
