# ===========================
# Redis StatefulSet
# ===========================
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: investment-assistant
  labels:
    app: redis
    component: cache
spec:
  serviceName: redis-headless
  replicas: 1
  selector:
    matchLabels:
      app: redis
      component: cache
  template:
    metadata:
      labels:
        app: redis
        component: cache
    spec:
      securityContext:
        fsGroup: 999
      containers:
      - name: redis
        image: redis:6
        # 기존 docker-compose.yml과 동일한 설정
        command: 
        - redis-server
        - --save
        - ""
        - --appendonly
        - "no"
        - --maxmemory
        - "256mb"
        - --maxmemory-policy
        - "allkeys-lru"
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: redis-data
          mountPath: /data
        - name: redis-config
          mountPath: /usr/local/etc/redis/redis.conf
          subPath: redis.conf
          readOnly: true
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
      - name: redis-config
        configMap:
          name: redis-config
          defaultMode: 0644
  volumeClaimTemplates:
  - metadata:
      name: redis-data
      labels:
        app: redis
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: local-path
      resources:
        requests:
          storage: 5Gi

---
# ===========================
# Redis Configuration ConfigMap
# ===========================
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: investment-assistant
  labels:
    app: redis
    component: cache
data:
  redis.conf: |
    # Redis Configuration for Airflow Backend
    # 기존 docker-compose.yml 설정 반영
    
    # Memory Management
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    
    # Persistence (disabled as per docker-compose)
    save ""
    appendonly no
    
    # Network
    bind 0.0.0.0
    port 6379
    timeout 0
    tcp-keepalive 300
    
    # General
    daemonize no
    supervised no
    pidfile /var/run/redis_6379.pid
    loglevel notice
    databases 16
    
    # Security (for development)
    # requirepass your-redis-password  # 필요시 활성화

---
# ===========================
# Redis Headless Service
# ===========================
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: investment-assistant
  labels:
    app: redis
    component: cache
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: redis
    component: cache

---
# ===========================
# Redis Service
# ===========================
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: investment-assistant
  labels:
    app: redis
    component: cache
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: redis
    component: cache