# ===========================
# PostgreSQL Database Secret
# ===========================
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: investment-assistant
  labels:
    app: postgresql
    component: database
type: Opaque
data:
  # 기존 docker-compose.yml과 동일한 계정 정보
  username: YWlyZmxvdw==        # airflow (base64)
  password: YWlyZmxvdw==        # airflow (base64)
  database: YWlyZmxvdw==        # airflow (base64)

---
# ===========================
# Airflow Secret Key
# ===========================
apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
  namespace: investment-assistant
  labels:
    app: airflow
    component: webserver
type: Opaque
data:
  # 기존 docker-compose.yml의 SECRET_KEY 값
  secret-key: ZGhSY21nSHFfUjdlVVZWMEU5RGJreXgtSzg4QlgycS1LWVVPQTM3bWRDYw==

---
# ===========================
# External API Keys Secret
# ===========================
apiVersion: v1
kind: Secret
metadata:
  name: api-keys
  namespace: investment-assistant
  labels:
    app: investment-assistant
    component: api-client
type: Opaque
data:
  # 실제 API 키들 (base64 인코딩됨)
  newsapi-key: MjRmNDEyODRkYzQ3NDI3ZGFjN2IyNjkxZGU5ZjVhOWI=                    # 24f41284dc47427dac7b2691de9f5a9b
  alphavantage-key: RldZSjZZRzdNSjJBT0NWSA==                                # FWYJ6YG7MJ2AOCVH
  finnhub-key: ZDA2dnY0OXIwMXFnMjZzYWoydDBkMDZ2djQ5cjAxcWcyNnNhajJ0Zw==        # d06vv49r01qg26saj2t0d06vv49r01qg26saj2tg
  fred-key: ZmVjMWM2ZWRiZjcwYTU0ZDIyMzExYzhiZjdmZGY3Mzg=                     # fec1c6edbf70a54d22311c8bf7fdf738
  fmp-key: MlAyM0xNTjlLc3dOVVRzTmlWY0pBMVlsamg0WHlaVW0=                      # 2P23LMN9KswNUTsNiVcJA1Yljh4XyZUm
  x-bearer-token: QUFBQUFBQUFBQUFBQUFBQUFBQUFBTGVOMHdFQUFBQUFlT3Y0Y2VRWSUyQiUyRnppTXNoTzdKZVh4RW5aRyUyQk0lM0QyaTB3MWpKQUhrVTBPRDFyeTZXdU5uTEVDM1R2Z0paYkg1QmczNnZnR3I1alJBb0s4aQ==  # X Bearer Token

---