INSERT INTO public.balance_sheet(
  symbol, fiscal_date_ending, reported_currency,
  total_assets, total_current_assets, cash_and_cash_equivalents,
  cash_and_short_term_investments, inventory, current_net_receivables,
  total_non_current_assets, property_plant_equipment, accumulated_depreciation_ppe,
  intangible_assets, intangible_excl_goodwill, goodwill,
  investments, long_term_investments, short_term_investments,
  other_current_assets, other_non_current_assets,
  total_liabilities, total_current_liabilities, current_accounts_payable,
  deferred_revenue, current_debt, short_term_debt,
  total_non_current_liabilities, capital_lease_obligations, long_term_debt,
  current_long_term_debt, long_term_debt_noncurrent, short_long_term_debt_total,
  other_current_liabilities, other_non_current_liabilities,
  total_shareholder_equity, treasury_stock, retained_earnings,
  common_stock, common_shares_outstanding, fetched_at
) VALUES (
  %(symbol)s, %(fiscalDateEnding)s::DATE, %(reportedCurrency)s,
  %(totalAssets)s::NUMERIC, %(totalCurrentAssets)s::NUMERIC, %(cashAndCashEquivalentsAtCarryingValue)s::NUMERIC,
  %(cashAndShortTermInvestments)s::NUMERIC, %(inventory)s::NUMERIC, %(currentNetReceivables)s::NUMERIC,
  %(totalNonCurrentAssets)s::NUMERIC, %(propertyPlantEquipment)s::NUMERIC, %(accumulatedDepreciationAmortizationPPE)s::NUMERIC,
  %(intangibleAssets)s::NUMERIC, %(intangibleAssetsExcludingGoodwill)s::NUMERIC, %(goodwill)s::NUMERIC,
  %(investments)s::NUMERIC, %(longTermInvestments)s::NUMERIC, %(shortTermInvestments)s::NUMERIC,
  %(otherCurrentAssets)s::NUMERIC, %(otherNonCurrentAssets)s::NUMERIC,
  %(totalLiabilities)s::NUMERIC, %(totalCurrentLiabilities)s::NUMERIC, %(currentAccountsPayable)s::NUMERIC,
  %(deferredRevenue)s::NUMERIC, %(currentDebt)s::NUMERIC, %(shortTermDebt)s::NUMERIC,
  %(totalNonCurrentLiabilities)s::NUMERIC, %(capitalLeaseObligations)s::NUMERIC, %(longTermDebt)s::NUMERIC,
  %(currentLongTermDebt)s::NUMERIC, %(longTermDebtNoncurrent)s::NUMERIC, %(shortLongTermDebtTotal)s::NUMERIC,
  %(otherCurrentLiabilities)s::NUMERIC, %(otherNonCurrentLiabilities)s::NUMERIC,
  %(totalShareholderEquity)s::NUMERIC, %(treasuryStock)s::NUMERIC, %(retainedEarnings)s::NUMERIC,
  %(commonStock)s::NUMERIC, %(commonStockSharesOutstanding)s::NUMERIC, NOW()
)
ON CONFLICT (symbol, fiscal_date_ending) DO UPDATE
  SET
    reported_currency                = EXCLUDED.reported_currency,
    total_assets                     = EXCLUDED.total_assets,
    total_current_assets             = EXCLUDED.total_current_assets,
    cash_and_cash_equivalents        = EXCLUDED.cash_and_cash_equivalents,
    cash_and_short_term_investments  = EXCLUDED.cash_and_short_term_investments,
    inventory                        = EXCLUDED.inventory,
    current_net_receivables          = EXCLUDED.current_net_receivables,
    total_non_current_assets         = EXCLUDED.total_non_current_assets,
    property_plant_equipment         = EXCLUDED.property_plant_equipment,
    accumulated_depreciation_ppe     = EXCLUDED.accumulated_depreciation_ppe,
    intangible_assets                = EXCLUDED.intangible_assets,
    intangible_excl_goodwill         = EXCLUDED.intangible_excl_goodwill,
    goodwill                         = EXCLUDED.goodwill,
    investments                      = EXCLUDED.investments,
    long_term_investments            = EXCLUDED.long_term_investments,
    short_term_investments           = EXCLUDED.short_term_investments,
    other_current_assets             = EXCLUDED.other_current_assets,
    other_non_current_assets         = EXCLUDED.other_non_current_assets,
    total_liabilities                = EXCLUDED.total_liabilities,
    total_current_liabilities        = EXCLUDED.total_current_liabilities,
    current_accounts_payable         = EXCLUDED.current_accounts_payable,
    deferred_revenue                 = EXCLUDED.deferred_revenue,
    current_debt                     = EXCLUDED.current_debt,
    short_term_debt                  = EXCLUDED.short_term_debt,
    total_non_current_liabilities    = EXCLUDED.total_non_current_liabilities,
    capital_lease_obligations        = EXCLUDED.capital_lease_obligations,
    long_term_debt                   = EXCLUDED.long_term_debt,
    current_long_term_debt           = EXCLUDED.current_long_term_debt,
    long_term_debt_noncurrent        = EXCLUDED.long_term_debt_noncurrent,
    short_long_term_debt_total       = EXCLUDED.short_long_term_debt_total,
    other_current_liabilities        = EXCLUDED.other_current_liabilities,
    other_non_current_liabilities    = EXCLUDED.other_non_current_liabilities,
    total_shareholder_equity         = EXCLUDED.total_shareholder_equity,
    treasury_stock                   = EXCLUDED.treasury_stock,
    retained_earnings                = EXCLUDED.retained_earnings,
    common_stock                     = EXCLUDED.common_stock,
    common_shares_outstanding        = EXCLUDED.common_shares_outstanding,
    fetched_at                       = NOW();
