-- upsert_x_posts.sql (업데이트된 버전)
-- Secondary Token 새 필드들 지원

INSERT INTO x_posts (
    tweet_id,
    author_id,
    text,
    created_at,
    lang,
    source_account,
    account_category,
    collection_source,
    retweet_count,
    reply_count,
    like_count,
    quote_count,
    bookmark_count,
    impression_count,
    hashtags,
    mentions,
    urls,
    cashtags,
    annotations,
    context_annotations,
    username,
    display_name,
    user_verified,
    user_followers_count,
    user_following_count,
    user_tweet_count,
    edit_history_tweet_ids,
    collected_at
) VALUES (
    %(tweet_id)s,
    %(author_id)s,
    %(text)s,
    %(created_at)s,
    %(lang)s,
    %(source_account)s,
    COALESCE(%(account_category)s, 'core_investors'),  -- 기본값 설정
    COALESCE(%(collection_source)s, 'primary_token'),  -- 기본값 설정
    %(retweet_count)s,
    %(reply_count)s,
    %(like_count)s,
    %(quote_count)s,
    %(bookmark_count)s,
    %(impression_count)s,
    %(hashtags)s,
    %(mentions)s,
    %(urls)s,
    %(cashtags)s,
    %(annotations)s,
    %(context_annotations)s,
    %(username)s,
    %(display_name)s,
    %(user_verified)s,
    %(user_followers_count)s,
    %(user_following_count)s,
    %(user_tweet_count)s,
    %(edit_history_tweet_ids)s,
    NOW()
)
ON CONFLICT (tweet_id)
DO UPDATE SET
    text = EXCLUDED.text,
    retweet_count = EXCLUDED.retweet_count,
    reply_count = EXCLUDED.reply_count,
    like_count = EXCLUDED.like_count,
    quote_count = EXCLUDED.quote_count,
    bookmark_count = EXCLUDED.bookmark_count,
    impression_count = EXCLUDED.impression_count,
    account_category = EXCLUDED.account_category,
    collection_source = EXCLUDED.collection_source,
    hashtags = EXCLUDED.hashtags,
    mentions = EXCLUDED.mentions,
    urls = EXCLUDED.urls,
    cashtags = EXCLUDED.cashtags,
    annotations = EXCLUDED.annotations,
    context_annotations = EXCLUDED.context_annotations,
    user_verified = EXCLUDED.user_verified,
    user_followers_count = EXCLUDED.user_followers_count,
    user_following_count = EXCLUDED.user_following_count,
    user_tweet_count = EXCLUDED.user_tweet_count,
    edit_history_tweet_ids = EXCLUDED.edit_history_tweet_ids,
    updated_at = NOW();