CREATE TABLE IF NOT EXISTS public.balance_sheet (
  symbol                           TEXT      NOT NULL,
  fiscal_date_ending               DATE      NOT NULL,
  reported_currency                TEXT,
  total_assets                     NUMERIC,
  total_current_assets             NUMERIC,
  cash_and_cash_equivalents        NUMERIC,
  cash_and_short_term_investments  NUMERIC,
  inventory                        NUMERIC,
  current_net_receivables          NUMERIC,
  total_non_current_assets         NUMERIC,
  property_plant_equipment         NUMERIC,
  accumulated_depreciation_ppe     NUMERIC,
  intangible_assets                NUMERIC,
  intangible_excl_goodwill         NUMERIC,
  goodwill                         NUMERIC,
  investments                      NUMERIC,
  long_term_investments            NUMERIC,
  short_term_investments           NUMERIC,
  other_current_assets             NUMERIC,
  other_non_current_assets         NUMERIC,
  total_liabilities                NUMERIC,
  total_current_liabilities        NUMERIC,
  current_accounts_payable         NUMERIC,
  deferred_revenue                 NUMERIC,
  current_debt                     NUMERIC,
  short_term_debt                  NUMERIC,
  total_non_current_liabilities    NUMERIC,
  capital_lease_obligations        NUMERIC,
  long_term_debt                   NUMERIC,
  current_long_term_debt           NUMERIC,
  long_term_debt_noncurrent        NUMERIC,
  short_long_term_debt_total       NUMERIC,
  other_current_liabilities        NUMERIC,
  other_non_current_liabilities    NUMERIC,
  total_shareholder_equity         NUMERIC,
  treasury_stock                   NUMERIC,
  retained_earnings                NUMERIC,
  common_stock                     NUMERIC,
  common_shares_outstanding        NUMERIC,
  fetched_at                       TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY (symbol, fiscal_date_ending)
);
