INSERT INTO public.sp500_top50 (symbol, company_name, sector, industry) VALUES
  ('AAPL','Apple Inc.','Information Technology','Technology Hardware, Storage & Peripherals'),
  ('MSFT','Microsoft Corp.','Information Technology','Systems Software'),
  ('AMZN','Amazon.com Inc.','Consumer Discretionary','Internet & Direct Marketing Retail'),
  ('NVDA','NVIDIA Corp.','Information Technology','Semiconductors'),
  ('GOOGL','Alphabet Inc. (Class A)','Communication Services','Interactive Media & Services'),
  ('TSLA','Tesla Inc.','Consumer Discretionary','Automobile Manufacturers'),
  ('META','Meta Platforms Inc.','Communication Services','Interactive Media & Services'),
  ('GOOG','Alphabet Inc. (Class C)','Communication Services','Interactive Media & Services'),
  ('BRK.B','Berkshire Hathaway Inc. (Class B)','Financials','Multi-Sector Holdings'),
  ('UNH','UnitedHealth Group Inc.','Health Care','Managed Health Care'),
  ('V','Visa Inc.','Information Technology','Data Processing & Outsourced Services'),
  ('JPM','JPMorgan Chase & Co.','Financials','Diversified Banks'),
  ('JNJ','Johnson & Johnson','Health Care','Pharmaceuticals'),
  ('WMT','Walmart Inc.','Consumer Staples','Hypermarkets & Super Centers'),
  ('PG','Procter & Gamble Co.','Consumer Staples','Household Products'),
  ('MA','Mastercard Inc.','Information Technology','Data Processing & Outsourced Services'),
  ('HD','Home Depot Inc.','Consumer Discretionary','Home Improvement Retail'),
  ('XOM','Exxon Mobil Corp.','Energy','Integrated Oil & Gas'),
  ('CVX','Chevron Corp.','Energy','Integrated Oil & Gas'),
  ('BAC','Bank of America Corp.','Financials','Diversified Banks'),
  ('PFE','Pfizer Inc.','Health Care','Pharmaceuticals'),
  ('MRK','Merck & Co. Inc.','Health Care','Pharmaceuticals'),
  ('KO','Coca-Cola Co.','Consumer Staples','Soft Drinks'),
  ('ABBV','AbbVie Inc.','Health Care','Pharmaceuticals'),
  ('INTC','Intel Corp.','Information Technology','Semiconductors'),
  ('ORCL','Oracle Corp.','Information Technology','Application Software'),
  ('CRM','Salesforce Inc.','Information Technology','Application Software'),
  ('AVGO','Broadcom Inc.','Information Technology','Semiconductors'),
  ('ADBE','Adobe Inc.','Information Technology','Application Software'),
  ('TXN','Texas Instruments Inc.','Information Technology','Semiconductors'),
  ('ABT','Abbott Laboratories','Health Care','Health Care Equipment'),
  ('MCD','McDonald''s Corp.','Consumer Discretionary','Restaurants'),
  ('NKE','Nike Inc.','Consumer Discretionary','Footwear'),
  ('COST','Costco Wholesale Corp.','Consumer Staples','Food Retail'),
  ('LLY','Eli Lilly & Co.','Health Care','Pharmaceuticals'),
  ('SBUX','Starbucks Corp.','Consumer Discretionary','Restaurants'),
  ('MDT','Medtronic PLC','Health Care','Health Care Equipment'),
  ('QCOM','Qualcomm Inc.','Information Technology','Semiconductors'),
  ('AMGN','Amgen Inc.','Health Care','Biotechnology'),
  ('HON','Honeywell International Inc.','Industrials','Industrial Conglomerates'),
  ('UNP','Union Pacific Corp.','Industrials','Railroads'),
  ('LOW','Lowe''s Cos. Inc.','Consumer Discretionary','Home Improvement Retail'),
  ('WFC','Wells Fargo & Co.','Financials','Diversified Banks'),
  ('UPS','United Parcel Service Inc.','Industrials','Air Freight & Logistics'),
  ('DIS','Walt Disney Co.','Communication Services','Movies & Entertainment'),
  ('CSCO','Cisco Systems Inc.','Information Technology','Communications Equipment'),
  ('NEE','NextEra Energy Inc.','Utilities','Independent Power Producers'),
  ('TMO','Thermo Fisher Scientific Inc.','Health Care','Life Sciences Tools & Services'),
  ('DHR','Danaher Corp.','Health Care','Life Sciences Tools & Services'),
  ('C','Citigroup Inc.','Financials','Diversified Banks')
ON CONFLICT (symbol) DO NOTHING;
