-- upsert_balance_sheet.sql
INSERT INTO balance_sheet (
    symbol,
    fiscalDateEnding,
    reportedCurrency,
    totalAssets,
    totalCurrentAssets,
    cashAndCashEquivalentsAtCarryingValue,
    cashAndShortTermInvestments,
    inventory,
    currentNetReceivables,
    totalNonCurrentAssets,
    propertyPlantEquipment,
    accumulatedDepreciationAmortizationPPE,
    intangibleAssets,
    intangibleAssetsExcludingGoodwill,
    goodwill,
    investments,
    longTermInvestments,
    shortTermInvestments,
    otherCurrentAssets,
    otherNonCurrentAssets,
    totalLiabilities,
    totalCurrentLiabilities,
    currentAccountsPayable,
    deferredRevenue,
    currentDebt,
    shortTermDebt,
    totalNonCurrentLiabilities,
    capitalLeaseObligations,
    longTermDebt,
    currentLongTermDebt,
    longTermDebtNoncurrent,
    shortLongTermDebtTotal,
    otherCurrentLiabilities,
    otherNonCurrentLiabilities,
    totalShareholderEquity,
    treasuryStock,
    retainedEarnings,
    commonStock,
    commonStockSharesOutstanding
) VALUES (
    %(symbol)s,
    %(fiscalDateEnding)s,
    %(reportedCurrency)s,
    %(totalAssets)s,
    %(totalCurrentAssets)s,
    %(cashAndCashEquivalentsAtCarryingValue)s,
    %(cashAndShortTermInvestments)s,
    %(inventory)s,
    %(currentNetReceivables)s,
    %(totalNonCurrentAssets)s,
    %(propertyPlantEquipment)s,
    %(accumulatedDepreciationAmortizationPPE)s,
    %(intangibleAssets)s,
    %(intangibleAssetsExcludingGoodwill)s,
    %(goodwill)s,
    %(investments)s,
    %(longTermInvestments)s,
    %(shortTermInvestments)s,
    %(otherCurrentAssets)s,
    %(otherNonCurrentAssets)s,
    %(totalLiabilities)s,
    %(totalCurrentLiabilities)s,
    %(currentAccountsPayable)s,
    %(deferredRevenue)s,
    %(currentDebt)s,
    %(shortTermDebt)s,
    %(totalNonCurrentLiabilities)s,
    %(capitalLeaseObligations)s,
    %(longTermDebt)s,
    %(currentLongTermDebt)s,
    %(longTermDebtNoncurrent)s,
    %(shortLongTermDebtTotal)s,
    %(otherCurrentLiabilities)s,
    %(otherNonCurrentLiabilities)s,
    %(totalShareholderEquity)s,
    %(treasuryStock)s,
    %(retainedEarnings)s,
    %(commonStock)s,
    %(commonStockSharesOutstanding)s
)
ON CONFLICT (symbol, fiscalDateEnding)
DO UPDATE SET
    reportedCurrency = EXCLUDED.reportedCurrency,
    totalAssets = EXCLUDED.totalAssets,
    totalCurrentAssets = EXCLUDED.totalCurrentAssets,
    cashAndCashEquivalentsAtCarryingValue = EXCLUDED.cashAndCashEquivalentsAtCarryingValue,
    cashAndShortTermInvestments = EXCLUDED.cashAndShortTermInvestments,
    inventory = EXCLUDED.inventory,
    currentNetReceivables = EXCLUDED.currentNetReceivables,
    totalNonCurrentAssets = EXCLUDED.totalNonCurrentAssets,
    propertyPlantEquipment = EXCLUDED.propertyPlantEquipment,
    accumulatedDepreciationAmortizationPPE = EXCLUDED.accumulatedDepreciationAmortizationPPE,
    intangibleAssets = EXCLUDED.intangibleAssets,
    intangibleAssetsExcludingGoodwill = EXCLUDED.intangibleAssetsExcludingGoodwill,
    goodwill = EXCLUDED.goodwill,
    investments = EXCLUDED.investments,
    longTermInvestments = EXCLUDED.longTermInvestments,
    shortTermInvestments = EXCLUDED.shortTermInvestments,
    otherCurrentAssets = EXCLUDED.otherCurrentAssets,
    otherNonCurrentAssets = EXCLUDED.otherNonCurrentAssets,
    totalLiabilities = EXCLUDED.totalLiabilities,
    totalCurrentLiabilities = EXCLUDED.totalCurrentLiabilities,
    currentAccountsPayable = EXCLUDED.currentAccountsPayable,
    deferredRevenue = EXCLUDED.deferredRevenue,
    currentDebt = EXCLUDED.currentDebt,
    shortTermDebt = EXCLUDED.shortTermDebt,
    totalNonCurrentLiabilities = EXCLUDED.totalNonCurrentLiabilities,
    capitalLeaseObligations = EXCLUDED.capitalLeaseObligations,
    longTermDebt = EXCLUDED.longTermDebt,
    currentLongTermDebt = EXCLUDED.currentLongTermDebt,
    longTermDebtNoncurrent = EXCLUDED.longTermDebtNoncurrent,
    shortLongTermDebtTotal = EXCLUDED.shortLongTermDebtTotal,
    otherCurrentLiabilities = EXCLUDED.otherCurrentLiabilities,
    otherNonCurrentLiabilities = EXCLUDED.otherNonCurrentLiabilities,
    totalShareholderEquity = EXCLUDED.totalShareholderEquity,
    treasuryStock = EXCLUDED.treasuryStock,
    retainedEarnings = EXCLUDED.retainedEarnings,
    commonStock = EXCLUDED.commonStock,
    commonStockSharesOutstanding = EXCLUDED.commonStockSharesOutstanding,
    fetched_at = NOW();