-- sql/upsert_company_overview.sql

INSERT INTO company_overview (
    batch_id,
    symbol, asset_type, name, description, cik, exchange, currency, country,
    sector, industry, address, official_site, fiscal_year_end, latest_quarter,
    market_capitalization, ebitda, pe_ratio, peg_ratio, book_value, 
    dividend_per_share, dividend_yield, eps, revenue_per_share_ttm,
    profit_margin, operating_margin_ttm, return_on_assets_ttm, return_on_equity_ttm,
    revenue_ttm, gross_profit_ttm, diluted_eps_ttm,
    quarterly_earnings_growth_yoy, quarterly_revenue_growth_yoy,
    analyst_target_price, trailing_pe, forward_pe, price_to_sales_ratio_ttm,
    price_to_book_ratio, ev_to_revenue, ev_to_ebitda, beta,
    week_52_high, week_52_low, day_50_moving_average, day_200_moving_average,
    shares_outstanding, dividend_date, ex_dividend_date,
    created_at
) VALUES (
    %(batch_id)s,
    %(symbol)s, %(asset_type)s, %(name)s, %(description)s, %(cik)s, %(exchange)s, 
    %(currency)s, %(country)s, %(sector)s, %(industry)s, %(address)s, %(official_site)s,
    %(fiscal_year_end)s, %(latest_quarter)s, %(market_capitalization)s, %(ebitda)s,
    %(pe_ratio)s, %(peg_ratio)s, %(book_value)s, %(dividend_per_share)s, %(dividend_yield)s,
    %(eps)s, %(revenue_per_share_ttm)s, %(profit_margin)s, %(operating_margin_ttm)s,
    %(return_on_assets_ttm)s, %(return_on_equity_ttm)s, %(revenue_ttm)s, %(gross_profit_ttm)s,
    %(diluted_eps_ttm)s, %(quarterly_earnings_growth_yoy)s, %(quarterly_revenue_growth_yoy)s,
    %(analyst_target_price)s, %(trailing_pe)s, %(forward_pe)s, %(price_to_sales_ratio_ttm)s,
    %(price_to_book_ratio)s, %(ev_to_revenue)s, %(ev_to_ebitda)s, %(beta)s,
    %(week_52_high)s, %(week_52_low)s, %(day_50_moving_average)s, %(day_200_moving_average)s,
    %(shares_outstanding)s, %(dividend_date)s, %(ex_dividend_date)s,
    NOW()
)
ON CONFLICT (batch_id, symbol)
DO UPDATE SET
    asset_type = EXCLUDED.asset_type,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    cik = EXCLUDED.cik,
    exchange = EXCLUDED.exchange,
    currency = EXCLUDED.currency,
    country = EXCLUDED.country,
    sector = EXCLUDED.sector,
    industry = EXCLUDED.industry,
    address = EXCLUDED.address,
    official_site = EXCLUDED.official_site,
    fiscal_year_end = EXCLUDED.fiscal_year_end,
    latest_quarter = EXCLUDED.latest_quarter,
    market_capitalization = EXCLUDED.market_capitalization,
    ebitda = EXCLUDED.ebitda,
    pe_ratio = EXCLUDED.pe_ratio,
    peg_ratio = EXCLUDED.peg_ratio,
    book_value = EXCLUDED.book_value,
    dividend_per_share = EXCLUDED.dividend_per_share,
    dividend_yield = EXCLUDED.dividend_yield,
    eps = EXCLUDED.eps,
    revenue_per_share_ttm = EXCLUDED.revenue_per_share_ttm,
    profit_margin = EXCLUDED.profit_margin,
    operating_margin_ttm = EXCLUDED.operating_margin_ttm,
    return_on_assets_ttm = EXCLUDED.return_on_assets_ttm,
    return_on_equity_ttm = EXCLUDED.return_on_equity_ttm,
    revenue_ttm = EXCLUDED.revenue_ttm,
    gross_profit_ttm = EXCLUDED.gross_profit_ttm,
    diluted_eps_ttm = EXCLUDED.diluted_eps_ttm,
    quarterly_earnings_growth_yoy = EXCLUDED.quarterly_earnings_growth_yoy,
    quarterly_revenue_growth_yoy = EXCLUDED.quarterly_revenue_growth_yoy,
    analyst_target_price = EXCLUDED.analyst_target_price,
    trailing_pe = EXCLUDED.trailing_pe,
    forward_pe = EXCLUDED.forward_pe,
    price_to_sales_ratio_ttm = EXCLUDED.price_to_sales_ratio_ttm,
    price_to_book_ratio = EXCLUDED.price_to_book_ratio,
    ev_to_revenue = EXCLUDED.ev_to_revenue,
    ev_to_ebitda = EXCLUDED.ev_to_ebitda,
    beta = EXCLUDED.beta,
    week_52_high = EXCLUDED.week_52_high,
    week_52_low = EXCLUDED.week_52_low,
    day_50_moving_average = EXCLUDED.day_50_moving_average,
    day_200_moving_average = EXCLUDED.day_200_moving_average,
    shares_outstanding = EXCLUDED.shares_outstanding,
    dividend_date = EXCLUDED.dividend_date,
    ex_dividend_date = EXCLUDED.ex_dividend_date;