INSERT INTO coingecko_coin_details (
    coingecko_id, symbol, name, web_slug,
    description_en, genesis_date, country_origin,
    homepage_url, blockchain_site, twitter_screen_name, facebook_username, 
    telegram_channel_identifier, subreddit_url, github_repos,
    image_thumb, image_small, image_large, categories,
    current_price_usd, current_price_krw, market_cap_usd, market_cap_rank, total_volume_usd,
    ath_usd, ath_change_percentage, ath_date, atl_usd, atl_change_percentage, atl_date,
    total_supply, circulating_supply, max_supply,
    price_change_24h_usd, price_change_percentage_24h, price_change_percentage_7d, price_change_percentage_30d,
    community_score, twitter_followers, reddit_subscribers, telegram_channel_user_count,
    developer_score, forks, stars, total_issues, closed_issues, commit_count_4_weeks,
    public_interest_score, liquidity_score, coingecko_last_updated, updated_at
) VALUES (
    %(coingecko_id)s, %(symbol)s, %(name)s, %(web_slug)s,
    %(description_en)s, %(genesis_date)s, %(country_origin)s,
    %(homepage_url)s, %(blockchain_site)s, %(twitter_screen_name)s, %(facebook_username)s,
    %(telegram_channel_identifier)s, %(subreddit_url)s, %(github_repos)s,
    %(image_thumb)s, %(image_small)s, %(image_large)s, %(categories)s,
    %(current_price_usd)s, %(current_price_krw)s, %(market_cap_usd)s, %(market_cap_rank)s, %(total_volume_usd)s,
    %(ath_usd)s, %(ath_change_percentage)s, %(ath_date)s, %(atl_usd)s, %(atl_change_percentage)s, %(atl_date)s,
    %(total_supply)s, %(circulating_supply)s, %(max_supply)s,
    %(price_change_24h_usd)s, %(price_change_percentage_24h)s, %(price_change_percentage_7d)s, %(price_change_percentage_30d)s,
    %(community_score)s, %(twitter_followers)s, %(reddit_subscribers)s, %(telegram_channel_user_count)s,
    %(developer_score)s, %(forks)s, %(stars)s, %(total_issues)s, %(closed_issues)s, %(commit_count_4_weeks)s,
    %(public_interest_score)s, %(liquidity_score)s, %(coingecko_last_updated)s, CURRENT_TIMESTAMP
)
ON CONFLICT (coingecko_id) DO UPDATE SET
    symbol = EXCLUDED.symbol,
    name = EXCLUDED.name,
    web_slug = EXCLUDED.web_slug,
    description_en = EXCLUDED.description_en,
    genesis_date = EXCLUDED.genesis_date,
    country_origin = EXCLUDED.country_origin,
    homepage_url = EXCLUDED.homepage_url,
    blockchain_site = EXCLUDED.blockchain_site,
    twitter_screen_name = EXCLUDED.twitter_screen_name,
    facebook_username = EXCLUDED.facebook_username,
    telegram_channel_identifier = EXCLUDED.telegram_channel_identifier,
    subreddit_url = EXCLUDED.subreddit_url,
    github_repos = EXCLUDED.github_repos,
    image_thumb = EXCLUDED.image_thumb,
    image_small = EXCLUDED.image_small,
    image_large = EXCLUDED.image_large,
    categories = EXCLUDED.categories,
    current_price_usd = EXCLUDED.current_price_usd,
    current_price_krw = EXCLUDED.current_price_krw,
    market_cap_usd = EXCLUDED.market_cap_usd,
    market_cap_rank = EXCLUDED.market_cap_rank,
    total_volume_usd = EXCLUDED.total_volume_usd,
    ath_usd = EXCLUDED.ath_usd,
    ath_change_percentage = EXCLUDED.ath_change_percentage,
    ath_date = EXCLUDED.ath_date,
    atl_usd = EXCLUDED.atl_usd,
    atl_change_percentage = EXCLUDED.atl_change_percentage,
    atl_date = EXCLUDED.atl_date,
    total_supply = EXCLUDED.total_supply,
    circulating_supply = EXCLUDED.circulating_supply,
    max_supply = EXCLUDED.max_supply,
    price_change_24h_usd = EXCLUDED.price_change_24h_usd,
    price_change_percentage_24h = EXCLUDED.price_change_percentage_24h,
    price_change_percentage_7d = EXCLUDED.price_change_percentage_7d,
    price_change_percentage_30d = EXCLUDED.price_change_percentage_30d,
    community_score = EXCLUDED.community_score,
    twitter_followers = EXCLUDED.twitter_followers,
    reddit_subscribers = EXCLUDED.reddit_subscribers,
    telegram_channel_user_count = EXCLUDED.telegram_channel_user_count,
    developer_score = EXCLUDED.developer_score,
    forks = EXCLUDED.forks,
    stars = EXCLUDED.stars,
    total_issues = EXCLUDED.total_issues,
    closed_issues = EXCLUDED.closed_issues,
    commit_count_4_weeks = EXCLUDED.commit_count_4_weeks,
    public_interest_score = EXCLUDED.public_interest_score,
    liquidity_score = EXCLUDED.liquidity_score,
    coingecko_last_updated = EXCLUDED.coingecko_last_updated,
    updated_at = CURRENT_TIMESTAMP;